# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cifuzz_job:
    name: CIFuzz Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set execute permissions for scripts
      run: |
        chmod +x name.sh build.sh run.sh

    - name: Build CIFuzz Docker Image
      run: |
        set -x
        ./build.sh

    - name: Build and run CIFuzz Docker container
      run: |
        docker build -t cifuzz-docker-image .
        
    - name: Run CIFuzz Docker container
      run: |
        docker run --rm cifuzz-docker-image
